const products = [
  {
    _id: '1',
    name: 'Be my Valentine',
    image: '/images/earings_red_heart.jpg',
    description: "Golden earrings with red hearts",
    category: 'earrings',
    price: 2500,
    countInStock: 1,
    rating: 4.8,
    numReviews: 10,
  },
  {
    _id: '2',
    name: 'Sky',
    image: '/images/earrings_blue_heart.PNG',
    description: "Golden earrings with blue hearts",
    category: 'earrings',
    price: 2500,
    countInStock: 3,
    rating: 4.9,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Van Clif',
    image: '/images/earrings_clever_gold.jpg',
    description: "Golden earrings with ceramics",
    category: 'earrings',
    price: 2500,
    countInStock: 2,
    rating: 5,
    numReviews: 15,
  },
  {
    _id: '4',
    name: 'VAHUE',
    image: '/images/vahue.JPG',
    description: "White choker with letters",
    category: 'necklaces',
    price: 2000,
    countInStock: 2,
    rating: 5,
    numReviews: 5,
  },
  {
    _id: '5',
    name: 'The Sea',
    image: '/images/ring.jpg',
    description: "Pearl ring with blue stone",
    category: 'rings',
    price: 1300,
    countInStock: 3,
    rating: 4.6,
    numReviews: 3,
  },
]

export default products
